# Generated by Django 3.2 on 2021-05-06 20:19

import channel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelid', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OtherLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('_id', models.CharField(default=channel.models.generate_id, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('channel_pic_url', models.CharField(default='https://vtube-test.s3.ap-south-1.amazonaws.com/channel.jpg', max_length=400)),
                ('channel_pic_key', models.CharField(default='channel.jpg', max_length=100)),
                ('channel_banner_url', models.CharField(default='https://vtube-test.s3.ap-south-1.amazonaws.com/banner1.jpg', max_length=400)),
                ('channel_banner_key', models.CharField(default='banner1.jpg', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='channel.ChannelCategory')),
                ('featured_channels', models.ManyToManyField(to='channel.FeaturedChannels')),
                ('followers', models.ManyToManyField(to='user.User')),
                ('other_links', models.ManyToManyField(to='channel.OtherLinks')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chnl_owned_by', to='user.user')),
            ],
        ),
    ]
