# Generated by Django 3.2 on 2021-05-15 08:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img_url',
            field=models.CharField(default=user.models.generate_profile_url, max_length=200, null=True),
        ),
    ]
