# Generated by Django 3.2 on 2021-05-06 20:19

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_by', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('_id', models.CharField(default=video.models.generate_id, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('views', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('thumb_url', models.CharField(max_length=400)),
                ('thumb_key', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=400)),
                ('video_key', models.CharField(max_length=100)),
                ('comments', models.ManyToManyField(to='video.VideoComment')),
                ('dislikes', models.ManyToManyField(to='video.DisLikes')),
                ('likes', models.ManyToManyField(to='video.Likes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_owned_by', to='channel.channel')),
                ('shares', models.ManyToManyField(to='video.Shares')),
                ('tags', models.ManyToManyField(to='video.Tags')),
                ('uploaded_by', models.ManyToManyField(to='channel.Channel')),
            ],
        ),
    ]
